In [55]:
import pandas as pd

In [56]:
price = pd.read_excel(r'C:\Users\keong\Desktop\IMTools\IMtool\IMtool app\master_files\master price.xlsx')
price['MonthYear'] = price['pur_code'].str.extract(r'(\d{4})')
price['pur_date'] = pd.to_datetime(price['MonthYear'], format='%m%y', errors='coerce')
price['pur_billing_date'] = pd.to_datetime(price['MonthYear'], format='%m%y', errors='coerce')

def find_last_digit_index(s):
    for i, char in enumerate(reversed(s)):
        if char.isdigit():
            return len(s) - i
    return -1  # if no digit found

# Apply the function to each cell in the column
price['max_num'] = price['pur_code'].apply(find_last_digit_index)

# Extract characters starting from 'max_num' index
price["slm_name"] = price.apply(
    lambda row: row["pur_code"][row["max_num"] :], 
    axis=1
)

price.drop(['MonthYear','max_num'],axis=1,inplace=True)
price['slm_name'] = price['slm_name'].replace("", "CJ7")
price.loc[price['slm_name']=='CJ7']
price.head()

  pur_code  pur_gold_cost   pur_date pur_billing_date slm_name
0   0111MG          128.0 2011-01-01       2011-01-01       MG
1  0111SLG          127.5 2011-01-01       2011-01-01      SLG
2   0112MH          156.5 2012-01-01       2012-01-01       MH
3   0112SH          155.0 2012-01-01       2012-01-01       SH
4  0112SLG          157.5 2012-01-01       2012-01-01      SLG

In [57]:
slm = pd.read_csv(r'C:\Users\keong\Desktop\IMTools\IMtool\IMtool app\master_files\salesman_mapping_file.csv')
slm.head()

       slm_id slm_name
0  SLM_100006       MG
1  SLM_100007      SLG
2  SLM_100008       MH
3  SLM_100009       SH
4  SLM_100010       YX

In [ ]:
price = pd.merge(price,slm,on='slm_name',how='left')
price.drop(['slm_name'],axis=1,inplace=True)
price.rename(columns={'slm_id': 'pur_slm_id'}, inplace=True)
price[['pur_labor_cost', 'pur_method', 'pur_official_invoice', 'pur_weight', 'pur_invoice_no', 'pur_payment_status']] = [0, 'CASH', 1, 0, 'NA', 'PAID']
price = price[['pur_slm_id', 'pur_gold_cost', 'pur_labor_cost', 'pur_method', 
               'pur_official_invoice', 'pur_date', 'pur_billing_date', 
               'pur_weight', 'pur_invoice_no', 'pur_code', 'pur_payment_status']]
pur_slm_id	pur_gold_cost	pur_labor_cost	pur_method	pur_official_invoice	pur_date	pur_billing_date	pur_weight	pur_invoice_no	pur_last_update	pur_created_at	pur_total_trade_in_amt	pur_total_cash_amt	pur_total_amt	pur_payment_status	pur_code

price.head()
price.to_excel(r'C:\Users\keong\Desktop\IMTools\IMtool\IMtool app\master_files\purchase_BulkInsert.xlsx',index=False)